name: Clox test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Generate build files
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_FLAGS=-fsanitize=address,undefined,leak -DCMAKE_EXE_LINKER_FLAGS=-fsanitize=address,undefined,leak -DDEBUG_TRACE_EXECUTION:BOOL=OFF -DDEBUG_PRINT_CODE:BOOL=OFF -DDEBUG_LOG_GC:BOOL=OFF -DDEBUG_STRESS_GC:BOOL=ON -DNAN_BOXING:BOOL=ON -G Ninja .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: ninja

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --extra-verbose

